# NumPy - Estudos e Anotações

Documentação: https://numpy.org/doc/1.26/user/index.html#user

### Importando a biblioteca NumPy

In [1]:
import numpy as np

## Fundamentos

### Criação de um array

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Cria um array de 2 dimensões (2D)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Retorna a quantidade de dimensões do array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Retorna a quantidade de colunas (1D) ou linhas e colunas (2D+)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Retorna o tipo de dados no array
a.dtype

dtype('int64')

In [7]:
# Retorna o tamanho em bytes de cada item no array
a.itemsize

8

In [8]:
# Retorna o tamanho total do array
a.nbytes

24

### Acessando/alterando elementos específicos, linhas, colunas etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Retorna um elemento específico [linha, coluna]
a[1,-2]

13

In [11]:
# Retorna uma linha específica. Neste caso, retorna todas as colunas (:) na primeira linha (slicing)
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Retorna uma coluna específica. Neste caso, retorna todas as linhas (:) na terceira coluna
a[:,2]

array([ 3, 10])

In [13]:
# Notação slicing - [startindex:endindex:step]
# Neste exemplo, retorna a primeira linha, da segunda até a última coluna, de 2 em 2
a[0, 1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### Exemplo de um array 3D:

In [15]:
# Um array contendo 2 arrays, com 2 arrays cada
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Retorna um elemento específico do array 3D (a ordem é de fora para dentro)
# Neste exemplo, retorna o segundo item do segundo array dentro do primeiro array
print(b[0,1,1])

4


In [17]:
# Substitui itens
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Inicializando diferentes tipos de arrays

In [18]:
# A função 'zeros' retorna um array/matriz de zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# A função 'ones' retorna um array/matriz de uns, e neste caso recebe o parâmetro 'dtype', como inteiro 
# (16 bits)
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [20]:
# A função 'full' retorna um array/matriz com um número à escolha
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [21]:
# A função 'full_like' funciona com a função 'full', e permite usar o shape de outro array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# A função 'random.rand' retorna números decimais aleatórios
np.random.rand(4,2)

array([[0.96157651, 0.4068977 ],
       [0.85990289, 0.77601041],
       [0.88550433, 0.04463166],
       [0.54024869, 0.56967836]])

In [23]:
# A função 'random.randint' retorna números inteiros aleatórios
np.random.randint(8, size=(3,3))

array([[3, 4, 5],
       [4, 5, 1],
       [6, 7, 1]])

In [24]:
# A função 'identity' retorna uma matriz identidade
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# A função 'repeat' retorna uma matriz de arrays repetidos
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:
arr2 = np.ones((5,5),dtype='int16')

z = np.zeros((3,3))
z[1,1] = 9
arr2[1:-1,1:-1] = z

print(arr2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Tenha cuidado quando copiar arrays

In [27]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [28]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Operações matemáticas

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [35]:
a**2

array([ 1,  4,  9, 16])

### Álgebra Linear

In [36]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [37]:
# Encontra a determinante
c = np.identity(3)
np.linalg.det(c)

1.0

### Funções estatísticas

In [38]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(stats)

1

In [40]:
np.max(stats)

6

In [41]:
np.sum(stats)

21

### Rearranjando arrays

In [42]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [43]:
# Empilhando vetores verticalmente
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Empilhando vetores horizontamente
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Diversos

##### Ler dados de um arquivo

In [45]:
filedata = np.genfromtxt('/kaggle/input/example-data/data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking e indexação avançada

In [46]:
print(filedata > 50)
filedata[filedata > 50]

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [47]:
## É possível indexar utilizando lista no NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [48]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [49]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [50]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

### Exercícios

In [51]:
# Criar uma matriz 6x5 com números de 1 a 30
m = np.array([np.arange(1,31)]).reshape(6,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [52]:
# Retornar os 2 primeiros elementos da terceira e quarta linha
print(m[2:4,0:2])

[[11 12]
 [16 17]]


In [53]:
# Retornar a diagonal de 2 a 20
print(m[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [54]:
# Retornar os 2 últimos itens da primeira, penúltima e última linha
print(m[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
